branches:
  only:
  - travis

language: objective-c
os: osx
osx_image: xcode11.3

cache:
  bundler: true
  cocoapods: true
  npm: true

before_install:
  - export LANG=it_IT.UTF-8
  #- brew update
  #- brew install cocoapods node

install:
  # install minimum set of dependencies to run tests and linters
  - npm install -g npm gulp bower

before_script:
  # update npm and bower dependencies
  - npm install
  - bower update

  # run linters and tests
  # if fails then build process stops
  # - gulp test

script:
  # install android SDK
  # -  wget http://dl.google.com/android/android-sdk_r24.4-macosx.zip
  # -  tar -xvf android-sdk_r24.4-macosx.zip
  
  # -  echo y | ./android-sdk-macosx/tools/android update sdk --no-ui --all --filter platform-tools
  # -  echo y | ./android-sdk-macosx/tools/android update sdk --no-ui --all --filter build-tools-23.0.2
  # -  echo y | ./android-sdk-macosx/tools/android update sdk --no-ui --all --filter android-23
  # -  echo y | ./android-sdk-macosx/tools/android update sdk --no-ui --all --filter extra-android-support
  # -  echo y | ./android-sdk-macosx/tools/android update sdk --no-ui --all --filter extra-android-m2repository
  # -  echo y | ./android-sdk-macosx/tools/android update sdk --no-ui --all --filter extra-google-m2repository
  
  # -  export ANDROID_HOME=./android-sdk-macosx
  # -  export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/23.0.2

  # install build dependecies
  - npm install -g cordova
  - npm install -g @ionic/cli native-run cordova-res
  - npm install --save-dev @angular-devkit/build-angular
  #- pod repo update #per far trovare onesignal
  
  # - install plugins etc.
  - ionic cordova prepare
  - ionic cordova platform rm android --save
  - ionic cordova platform add ios@latest --save
  - ionic cordova plugin add onesignal-cordova-plugin
  - ionic cordova plugin add cordova-plugin-ionic-webview@latest

  # build Android and iOS packages
  #- cordova build android --release
  #- ionic cordova build ios --device --release
  - ionic cordova build ios --emulator --debug

after_success:
  # generate documentation
  # - gulp doc

deploy:
  # deploy build to s3, testflight etc.